// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Email de contato documents
 */
interface ContactEmailDocumentData {
  /**
   * Email field in *Email de contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_email.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Email de contato document from Prismic
 *
 * - **API ID**: `contact_email`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactEmailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactEmailDocumentData>,
    "contact_email",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | FormSlice
  | ImageSlice
  | TestimonialsSlice
  | PostGallerySlice
  | TextSlice
  | HeroSlice
  | HeaderSlice
  | CallToActionSlice;

/**
 * Content for Página documents
 */
interface PageDocumentData {
  /**
   * Título field in *Página*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Página Pai field in *Página*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Mostrar título da página field in *Página*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: page.show_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_title: prismic.BooleanField;

  /**
   * Slice Zone field in *Página*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Título field in *Página*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título de página utilizado por redes sociais e motores de busca
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Descrição field in *Página*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Um resumo curto da página
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Imagem field in *Página*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Página document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PostDocumentDataSlicesSlice =
  | ImageSlice
  | SplitterSlice
  | TextSlice
  | HeroSlice
  | CallToActionSlice;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Título field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Thumbnail field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice> /**
   * Meta Título field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Título de página utilizado por redes sociais e motores de busca
   * - **API ID Path**: post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Descrição field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Um resumo curto da página
   * - **API ID Path**: post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Imagem field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Content for Rede Social documents
 */
interface SocialMediaDocumentData {
  /**
   * Link field in *Rede Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Rede Social document from Prismic
 *
 * - **API ID**: `social_media`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SocialMediaDocumentData>,
    "social_media",
    Lang
  >;

export type AllDocumentTypes =
  | ContactEmailDocument
  | PageDocument
  | PostDocument
  | SocialMediaDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Texto field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Destino field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.destination
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination: prismic.LinkField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → Centralizada → Primary*
 */
export interface CallToActionSliceCenterPrimary {
  /**
   * Texto field in *CallToAction → Centralizada → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.center.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Destino field in *CallToAction → Centralizada → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.center.primary.destination
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  destination: prismic.LinkField;
}

/**
 * Centralizada variation for CallToAction Slice
 *
 * - **API ID**: `center`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceCenter = prismic.SharedSliceVariation<
  "center",
  Simplify<CallToActionSliceCenterPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceCenter;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Item in *Form → Default → Primary → Campos*
 */
export interface FormSliceDefaultPrimaryFieldsItem {
  /**
   * Título field in *Form → Default → Primary → Campos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.fields[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tipo field in *Form → Default → Primary → Campos*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Tipo do campo a ser preenchido
   * - **API ID Path**: form.default.primary.fields[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    | "Texto curto"
    | "Texto longo (múltiplas linhas)"
    | "Número"
    | "E-mail"
    | "Data"
    | "Número de Telefone"
  >;

  /**
   * Obrigatório? field in *Form → Default → Primary → Campos*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: form.default.primary.fields[].required
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  required: prismic.BooleanField;
}

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Campos field in *Form → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.fields[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  fields: prismic.GroupField<Simplify<FormSliceDefaultPrimaryFieldsItem>>;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Título field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtítulo field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Botões*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Link do botão field in *Hero → Default → Primary → Botões*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Texto do botão field in *Hero → Default → Primary → Botões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *Hero → Default → Primary → Carrossel de imagens*
 */
export interface HeroSliceDefaultPrimaryCarouselItem {
  /**
   * Imagem field in *Hero → Default → Primary → Carrossel de imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Hero → Estilo Revista - Mobile e Desk → Primary → Botões*
 */
export interface HeroSliceMagazineMobileAndDesktopPrimaryButtonsItem {
  /**
   * Link do botão field in *Hero → Estilo Revista - Mobile e Desk → Primary → Botões*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Texto do botão field in *Hero → Estilo Revista - Mobile e Desk → Primary → Botões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.buttons[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *Hero → Estilo Revista - Mobile → Primary → Botões*
 */
export interface HeroSliceMagazineMobilePrimaryButtonsItem {
  /**
   * Link do botão field in *Hero → Estilo Revista - Mobile → Primary → Botões*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Texto do botão field in *Hero → Estilo Revista - Mobile → Primary → Botões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.buttons[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *Hero → Estilo Revista - Mobile → Primary → Carrossel de imagens*
 */
export interface HeroSliceMagazineMobilePrimaryCarouselItem {
  /**
   * Imagem field in *Hero → Estilo Revista - Mobile → Primary → Carrossel de imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Hero → Produtos → Primary → Botões*
 */
export interface HeroSliceProductsPrimaryButtonsItem {
  /**
   * Link do botão field in *Hero → Produtos → Primary → Botões*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Texto do botão field in *Hero → Produtos → Primary → Botões*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.buttons[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *Hero → Produtos → Primary → Carrossel de imagens*
 */
export interface HeroSliceProductsPrimaryCarouselItem {
  /**
   * Texto destacado field in *Hero → Produtos → Primary → Carrossel de imagens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.carousel[].highlighted_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  highlighted_text: prismic.RichTextField;

  /**
   * Imagem field in *Hero → Produtos → Primary → Carrossel de imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Título field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Botões field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>;

  /**
   * Carrossel de imagens field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCarouselItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Estilo Revista - Mobile e Desk → Primary*
 */
export interface HeroSliceMagazineMobileAndDesktopPrimary {
  /**
   * Título field in *Hero → Estilo Revista - Mobile e Desk → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Posição do título field in *Hero → Estilo Revista - Mobile e Desk → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.is_title_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_title_left: prismic.BooleanField;

  /**
   * Texto field in *Hero → Estilo Revista - Mobile e Desk → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Posição do texto field in *Hero → Estilo Revista - Mobile e Desk → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.is_text_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_text_left: prismic.BooleanField;

  /**
   * Botões field in *Hero → Estilo Revista - Mobile e Desk → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<
    Simplify<HeroSliceMagazineMobileAndDesktopPrimaryButtonsItem>
  >;

  /**
   * Imagem field in *Hero → Estilo Revista - Mobile e Desk → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobileAndDesktop.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Estilo Revista - Mobile e Desk variation for Hero Slice
 *
 * - **API ID**: `magazineMobileAndDesktop`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceMagazineMobileAndDesktop = prismic.SharedSliceVariation<
  "magazineMobileAndDesktop",
  Simplify<HeroSliceMagazineMobileAndDesktopPrimary>,
  never
>;

/**
 * Primary content in *Hero → Estilo Revista - Mobile → Primary*
 */
export interface HeroSliceMagazineMobilePrimary {
  /**
   * Título field in *Hero → Estilo Revista - Mobile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Hero → Estilo Revista - Mobile → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Posição do texto field in *Hero → Estilo Revista - Mobile → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.magazineMobile.primary.is_text_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_text_left: prismic.BooleanField;

  /**
   * Botões field in *Hero → Estilo Revista - Mobile → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<
    Simplify<HeroSliceMagazineMobilePrimaryButtonsItem>
  >;

  /**
   * Imagem Mobile field in *Hero → Estilo Revista - Mobile → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.mobile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_image: prismic.ImageField<never>;

  /**
   * Carrossel de imagens field in *Hero → Estilo Revista - Mobile → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.magazineMobile.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<HeroSliceMagazineMobilePrimaryCarouselItem>
  >;
}

/**
 * Estilo Revista - Mobile variation for Hero Slice
 *
 * - **API ID**: `magazineMobile`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceMagazineMobile = prismic.SharedSliceVariation<
  "magazineMobile",
  Simplify<HeroSliceMagazineMobilePrimary>,
  never
>;

/**
 * Primary content in *Hero → Produtos → Primary*
 */
export interface HeroSliceProductsPrimary {
  /**
   * Antes do texto destacado field in *Hero → Produtos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.before_highlighted_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  before_highlighted_text: prismic.RichTextField;

  /**
   * Depois do texto detacado field in *Hero → Produtos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.after_highlighted_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  after_highlighted_text: prismic.RichTextField;

  /**
   * Botões field in *Hero → Produtos → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceProductsPrimaryButtonsItem>>;

  /**
   * Carrossel de imagens field in *Hero → Produtos → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.products.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<Simplify<HeroSliceProductsPrimaryCarouselItem>>;
}

/**
 * Produtos variation for Hero Slice
 *
 * - **API ID**: `products`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceProducts = prismic.SharedSliceVariation<
  "products",
  Simplify<HeroSliceProductsPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceMagazineMobileAndDesktop
  | HeroSliceMagazineMobile
  | HeroSliceProducts;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Image → Imagens - Estilo Colunas → Primary → Imagens*
 */
export interface ImageSliceImagesInColumnsPrimaryImagesItem {
  /**
   * Imagem field in *Image → Imagens - Estilo Colunas → Primary → Imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.imagesInColumns.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Image → Imagens - Estilo Alvenaria → Primary → Imagens*
 */
export interface ImageSliceImagesInMasonryPrimaryImagesItem {
  /**
   * Imagem field in *Image → Imagens - Estilo Alvenaria → Primary → Imagens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.imagesInMasonry.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Image → Fullscreen → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Imagem field in *Image → Fullscreen → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Alterar tamanho da imagem field in *Image → Fullscreen → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image.default.primary.change_image_size
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  change_image_size: prismic.BooleanField;

  /**
   * Manter proporção? field in *Image → Fullscreen → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.keep_aspect_ratio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  keep_aspect_ratio: prismic.SelectField<
    | "Largura (ajustar altura automaticamente)"
    | "Altura (ajustar largura automaticamente)"
    | "Não manter proporção"
  >;

  /**
   * Altura da imagem (px) field in *Image → Fullscreen → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image_height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  image_height: prismic.NumberField;

  /**
   * Largura da imagem (px) field in *Image → Fullscreen → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  image_width: prismic.NumberField;
}

/**
 * Fullscreen variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Imagens - Estilo Colunas → Primary*
 */
export interface ImageSliceImagesInColumnsPrimary {
  /**
   * Número de colunas field in *Image → Imagens - Estilo Colunas → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Número de colunas mostradas no PC
   * - **API ID Path**: image.imagesInColumns.primary.col_quantity
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  col_quantity: prismic.NumberField;

  /**
   * Altura das imagens (px) field in *Image → Imagens - Estilo Colunas → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Altura utilizada para que todas as imagens tenham o mesmo tamanho
   * - **API ID Path**: image.imagesInColumns.primary.image_height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  image_height: prismic.NumberField;

  /**
   * Imagens field in *Image → Imagens - Estilo Colunas → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.imagesInColumns.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliceImagesInColumnsPrimaryImagesItem>
  >;
}

/**
 * Imagens - Estilo Colunas variation for Image Slice
 *
 * - **API ID**: `imagesInColumns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceImagesInColumns = prismic.SharedSliceVariation<
  "imagesInColumns",
  Simplify<ImageSliceImagesInColumnsPrimary>,
  never
>;

/**
 * Primary content in *Image → Imagens - Estilo Alvenaria → Primary*
 */
export interface ImageSliceImagesInMasonryPrimary {
  /**
   * Largura da coluna (px) field in *Image → Imagens - Estilo Alvenaria → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: image.imagesInMasonry.primary.col_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  col_width: prismic.NumberField;

  /**
   * Imagens field in *Image → Imagens - Estilo Alvenaria → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.imagesInMasonry.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliceImagesInMasonryPrimaryImagesItem>
  >;
}

/**
 * Imagens - Estilo Alvenaria variation for Image Slice
 *
 * - **API ID**: `imagesInMasonry`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceImagesInMasonry = prismic.SharedSliceVariation<
  "imagesInMasonry",
  Simplify<ImageSliceImagesInMasonryPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation =
  | ImageSliceDefault
  | ImageSliceImagesInColumns
  | ImageSliceImagesInMasonry;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *PostGallery → Default → Primary*
 */
export interface PostGallerySliceDefaultPrimary {
  /**
   * Título field in *PostGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtítulo field in *PostGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post_gallery.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Número de colunas field in *PostGallery → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Número de colunas mostradas no PC
   * - **API ID Path**: post_gallery.default.primary.cols
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  cols: prismic.NumberField;

  /**
   * Mostrar título dos posts field in *PostGallery → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: post_gallery.default.primary.show_post_titles
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_post_titles: prismic.BooleanField;
}

/**
 * Default variation for PostGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PostGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PostGallery*
 */
type PostGallerySliceVariation = PostGallerySliceDefault;

/**
 * PostGallery Shared Slice
 *
 * - **API ID**: `post_gallery`
 * - **Description**: PostGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostGallerySlice = prismic.SharedSlice<
  "post_gallery",
  PostGallerySliceVariation
>;

/**
 * Primary content in *Splitter → Default → Primary*
 */
export interface SplitterSliceDefaultPrimary {
  /**
   * Antes field in *Splitter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: splitter.default.primary.before
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  before: prismic.ImageField<never>;

  /**
   * Depois field in *Splitter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: splitter.default.primary.after
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  after: prismic.ImageField<never>;
}

/**
 * Default variation for Splitter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Splitter*
 */
type SplitterSliceVariation = SplitterSliceDefault;

/**
 * Splitter Shared Slice
 *
 * - **API ID**: `splitter`
 * - **Description**: Splitter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitterSlice = prismic.SharedSlice<
  "splitter",
  SplitterSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Depoimentos*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Imagem do autor field in *Testimonials → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Nome do autor field in *Testimonials → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].author_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author_name: prismic.RichTextField;

  /**
   * Citação field in *Testimonials → Default → Primary → Depoimentos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Texto field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Depoimentos field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *Text → Texto → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Texto field in *Text → Texto → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Texto variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Texto & Imagem → Primary*
 */
export interface TextSliceTextAndImagePrimary {
  /**
   * Posição do texto field in *Text → Texto & Imagem → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.textAndImage.primary.is_text_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_text_left: prismic.BooleanField;

  /**
   * Texto field in *Text → Texto & Imagem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textAndImage.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Imagem field in *Text → Texto & Imagem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textAndImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Texto & Imagem variation for Text Slice
 *
 * - **API ID**: `textAndImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTextAndImage = prismic.SharedSliceVariation<
  "textAndImage",
  Simplify<TextSliceTextAndImagePrimary>,
  never
>;

/**
 * Primary content in *Text → Texto & Cabeçalho → Primary*
 */
export interface TextSliceTextAndHeaderPrimary {
  /**
   * Posição do texto field in *Text → Texto & Cabeçalho → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.textAndHeader.primary.is_text_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_text_left: prismic.BooleanField;

  /**
   * Texto field in *Text → Texto & Cabeçalho → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textAndHeader.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Cabeçalho field in *Text → Texto & Cabeçalho → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textAndHeader.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;
}

/**
 * Texto & Cabeçalho variation for Text Slice
 *
 * - **API ID**: `textAndHeader`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTextAndHeader = prismic.SharedSliceVariation<
  "textAndHeader",
  Simplify<TextSliceTextAndHeaderPrimary>,
  never
>;

/**
 * Primary content in *Text → Texto + Cabeçalho & Imagem → Primary*
 */
export interface TextSliceTextWithHeaderAndImagePrimary {
  /**
   * Posição do texto field in *Text → Texto + Cabeçalho & Imagem → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text.textWithHeaderAndImage.primary.is_text_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_text_left: prismic.BooleanField;

  /**
   * Texto field in *Text → Texto + Cabeçalho & Imagem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textWithHeaderAndImage.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Cabeçalho field in *Text → Texto + Cabeçalho & Imagem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textWithHeaderAndImage.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * Imagem field in *Text → Texto + Cabeçalho & Imagem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text.textWithHeaderAndImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Texto + Cabeçalho & Imagem variation for Text Slice
 *
 * - **API ID**: `textWithHeaderAndImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTextWithHeaderAndImage = prismic.SharedSliceVariation<
  "textWithHeaderAndImage",
  Simplify<TextSliceTextWithHeaderAndImagePrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation =
  | TextSliceDefault
  | TextSliceTextAndImage
  | TextSliceTextAndHeader
  | TextSliceTextWithHeaderAndImage;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactEmailDocument,
      ContactEmailDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PostDocument,
      PostDocumentData,
      PostDocumentDataSlicesSlice,
      SocialMediaDocument,
      SocialMediaDocumentData,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceCenterPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceCenter,
      FormSlice,
      FormSliceDefaultPrimaryFieldsItem,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimaryCarouselItem,
      HeroSliceDefaultPrimary,
      HeroSliceMagazineMobileAndDesktopPrimaryButtonsItem,
      HeroSliceMagazineMobileAndDesktopPrimary,
      HeroSliceMagazineMobilePrimaryButtonsItem,
      HeroSliceMagazineMobilePrimaryCarouselItem,
      HeroSliceMagazineMobilePrimary,
      HeroSliceProductsPrimaryButtonsItem,
      HeroSliceProductsPrimaryCarouselItem,
      HeroSliceProductsPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceMagazineMobileAndDesktop,
      HeroSliceMagazineMobile,
      HeroSliceProducts,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceImagesInColumnsPrimaryImagesItem,
      ImageSliceImagesInColumnsPrimary,
      ImageSliceImagesInMasonryPrimaryImagesItem,
      ImageSliceImagesInMasonryPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceImagesInColumns,
      ImageSliceImagesInMasonry,
      PostGallerySlice,
      PostGallerySliceDefaultPrimary,
      PostGallerySliceVariation,
      PostGallerySliceDefault,
      SplitterSlice,
      SplitterSliceDefaultPrimary,
      SplitterSliceVariation,
      SplitterSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceTextAndImagePrimary,
      TextSliceTextAndHeaderPrimary,
      TextSliceTextWithHeaderAndImagePrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceTextAndImage,
      TextSliceTextAndHeader,
      TextSliceTextWithHeaderAndImage,
    };
  }
}
