// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  post_gallery: dynamic(() => import("./PostGallery")),
  splitter: dynamic(() => import("./Splitter")),
  testimonials: dynamic(() => import("./Testimonials")),
  text: dynamic(() => import("./Text")),
};
