// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  divider: dynamic(() => import("./Divider")),
  form: dynamic(() => import("./Form")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  post_gallery: dynamic(() => import("./PostGallery")),
  splitter: dynamic(() => import("./Splitter")),
  testimonials: dynamic(() => import("./Testimonials")),
  text: dynamic(() => import("./Text")),
};
